# Generated by Django 4.2.7 on 2024-05-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=10)),
                ('academic_year', models.IntegerField(default=2024)),
                ('dob', models.DateField()),
                ('unique_student_id', models.CharField(max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('unique_teacher_id', models.CharField(max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('students', models.ManyToManyField(blank=True, to='school_back.student')),
                ('teachers', models.ManyToManyField(blank=True, to='school_back.teacher')),
            ],
        ),
    ]
