# Generated by Django 4.2.7 on 2024-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
